# SPDX-FileCopyrightText: 2024 shadPS4 Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later

name: Build shadPS4 Windows Qt

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows-qt:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          modules: qtmultimedia

      - name: Configure CMake
        run: cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_QT_GUI=ON -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Deploy Qt DLLs
        run: |
          mkdir upload
          move build/shadPS4.exe upload
          "${{ env.Qt6_DIR }}\\bin\\windeployqt.exe" upload/shadPS4.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shadps4-win64-qt
          path: upload/